CREATE TABLE CUSTOMER (
     ID  SERIAL PRIMARY KEY,
     SCHEMA_NAME varchar(63) NOT NULL,
     COMPANY_NAME varchar(100) NOT NULL,
     TRADE_NAME varchar(100) NOT NULL,
     EMAIL varchar(100) NOT NULL,
     ACTIVE BOOLEAN DEFAULT TRUE
);
