CREATE TABLE TEMPLATE
(
    ID                  SERIAL PRIMARY KEY,
    NAME                VARCHAR(100) NOT NULL,
    TEMPLATE_SCM_ID     SERIAL       NOT NULL REFERENCES SCM (ID),
    TEMPLATE_REPOSITORY VARCHAR(100) NOT NULL,
    TEMPLATE_BRANCH     VARCHAR(100) NOT NULL,
    TARGET_SCM_ID       SERIAL       NOT NULL REFERENCES SCM (ID),
    TARGET_BRANCH       VARCHAR(100) NOT NULL
);

CREATE TABLE TEMPLATE_STATUS
(
    ID       SERIAL PRIMARY KEY,
    UUID     UUID         NOT NULL,
    STEP     VARCHAR(100) NOT NULL,
    MESSAGE  TEXT         NOT NULL,
    IS_ERROR BOOLEAN      NOT NULL DEFAULT FALSE
);
