CREATE TABLE K8S_CLUSTER (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CONNECTION_TYPE VARCHAR(50) NOT NULL,
    URL VARCHAR(255),
    TOKEN TEXT,
    USERNAME VARCHAR(50),
    PASSWORD TEXT,
    VALIDATE_SSL BOOLEAN
);